### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by chaos234** [jimdoescode/CodeIgniter-Dropbox-API-Library#13] opened 2014-12-11 06:25 UTC
I duno why this is listed at the dropbox webpage but it's the secound project which is out of date and uses depricated SHA1 Hash instead of SHA256 and the newer API ans OAuth 2 version.

Please fix this!

Oh and don't write source as the following:

class blabla
{

}

This is false written OOP!

You have to write it like this:

class blabla {

public function blubblub(array $arr, $param) {

if ($param == true) {

//do this
} else {

/do smth.

}

}

This is the right OOP Structure for all brakets and no other own builds otherwise you don't have the rigth to call this OOP-Scripts!

Oh and don't try to use JSON in the newer version. I hate it because it's not for webpages so please try to use a simple REST API call

**Comment by jimdoescode** [comment] 2014-12-11 14:46
I'm not sure what the issue is you're raising. It also doesn't seem like you really understand what object oriented programming is. All that said please issue a pull request addressing whatever it is you're concerned about and it will be seriously considered. 

According to the documentation OAuth 1 _is_ still supported even though OAuth 2 is preferred so using OAuth 1 will still work. 

I'm closing this as it doesn't really address an actual issue.

**Closed as completed by jimdoescode** 2014-12-11 14:46 UTC

**Comment by Kendysond** [comment] 2015-04-07 13:48
Please don't promote your own libraries here. - Jimdoescode
