### ISSUE TITLE
Expecting A file Upload Error

### ISSUE THREAD

**Issue by Kendysond** [jimdoescode/CodeIgniter-Dropbox-API-Library#15] opened 2015-04-04 12:56 UTC
$dbpath = 'backup';
        $filepath = $save;
        $uploaded = $this->dropbox->add($dbpath, $filepath);

Error Result
stdClass Object ( [error] => stdClass Object ( [file] => Expecting a file upload ) )

**Comment by jimdoescode** [comment] 2015-04-04 17:12
I'm not able to reproduce this. Here's a thread for a different PHP lib that says the needed to update their PHP version. https://github.com/BenExile/Dropbox/issues/67

I'm going to close this since I can't replicate it.

**Closed as completed by jimdoescode** 2015-04-04 17:12 UTC

**Comment by ghost** [comment] 2016-08-08 21:34
On line 226 in the libraries/Dropbox.php file I replaced the initial code with 
return $this->_post_request($uri, array('file'=>new CURLFile($filepath)), $specialhost);
and it has worked for me. I hope this solves your issue.
